id: P007926
initial_creation_type: ocr
source_metadata:
  id: bdr:W687
  title: རྩིས་གཞུང་པད་དཀར་ཞལ་ལུང་།
  author: ''
  volumes:
    589cd0c1f4e246e6a14a9c0f76eb7b68:
      image_group_id: I1KG22097
      title: ''
      volume_number: 1
      total_pages: 860
ebook_metadata:
  title: རྩིས་གཞུང་པད་དཀར་ཞལ་ལུང་།
  author: ''
  sku: P007926
  cover: cover.jpg
  layers:
  - pagination
