id: I914E4FCA
legacy_id: P007926
ocr_import_info:
  bdrc_scan_id: W687
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T17:50:47'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:11:07.742086+00:00'
last_modified: 2022-09-04 11:11:33.723287
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W687
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW687
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྩིས་གཞུང་པད་དཀར་ཞལ་ལུང་།
  author: ཕུག་པ་ལྷུན་གྲུབ་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.5285399195871929
  ocr_word_median_confidence_index: 0.5
quality: null
bases:
  I1KG22097:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22097
      total_pages: 860
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG22097.txt
    statistics:
      ocr_word_median_confidence_index: 0.5
      ocr_word_mean_confidence_index: 0.5285399195871929
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
