id: I914E4FCA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T17:56:00+00:00'
last_modified: '2022-06-09T07:35:18.382343+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W687
  title: རྩིས་གཞུང་པད་དཀར་ཞལ་ལུང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C497:
      image_group_id: I1KG22097
      title: Volume 1 of rtsis gzhung pad dkar zhal lung
      total_pages: 860
      order: 1
      base_file: C497.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
